### ISSUE TITLE
Does new Installer require not settings for Geo??

### ISSUE THREAD

**Issue by bikramtpa** [kersing/multitech-installer#10]
As I can remember, the old installer needed Geo location to be set. But just a minute before I was trying to reinstall, didnt ask for geo location. Does that mean, I dont need to set Geo anymore???

**Comment by kersing** [comment]
Gateway position information can be configured in the TTN console. TTN requested to send only real GPS information, not fake GPS information from gateways to the back-end so there is no need to configure this.

**Comment by bikramtpa** [comment]
Thank your :)

**Comment by xenek** [comment]
Hi, thx for great work!

I have an Mlinux Conduit, with ublox GPS. 
`vi /etc/default/gpsd` shows it's configured and enabled. 
`gpsmon` shows it has a fix
port used by gpsd is /dev/ttyXRUSB2

install.sh doesn't ask if I want to use the GPS.
I edited localconf.json after install to enable GPS.
```
        "gps": true,
        "fake_gps": false,
```
but still TTN site doesn't show location according to gpsd fix, only shows default location based (I think) from public IP. Is there something I have missed? 

x

**Comment by bikramtpa** [comment]
For me it took couple of minutes to get new changes in TTN, and as soon as device was online I saw those changes, I also tried a cheatsheet, I guess created new account with same settings but with different GEO with multiple accounts, because I had to present the prototype at different locations, but even not changing GEO did not affect I guess,  No more GEO location is need in new version but on client side only.

**Comment by kersing** [comment]
gpsd is not used. You will need to stop gpsd and specify the correct device in the configuration:
"gps_tty_path": "/dev/ttyXRUSB2"

**Comment by xenek** [comment]
Thanks, that helped. I stopped gpsd following instructions at:

http://www.multitech.net/developer/software/mlinux/using-mlinux/gpsgnss-on-conduit/

Now, my log shows this:
```
##### 2017-12-20 03:07:42 GMT #####
### [UPSTREAM] ###
# RF packets received by concentrator: 3
# CRC_OK: 100.00%, CRC_FAIL: 0.00%, NO_CRC: 0.00%
# RF packets forwarded: 3 (69 bytes)
# PUSH_DATA datagrams sent: 0 (0 bytes)
# PUSH_DATA acknowledged: 0.00%
### [DOWNSTREAM] ###
# PULL_DATA sent: 0 (0.00% acknowledged)
# PULL_RESP(onse) datagrams received: 0 (0 bytes)
# RF packets sent to concentrator: 0 (0 bytes)
# TX errors: 0
### BEACON IS DISABLED!
### [JIT] ###
# INFO: JIT queue contains 0 packets.
# INFO: JIT queue contains 0 beacons.
### [GPS] ###
# Valid gps time reference (age: 1 sec)
# System GPS coordinates: latitude -16.92196, longitude 145.75470, altitude 26 m
### [PERFORMANCE] ###
# Upstream radio packet quality: 100.00%.
# Semtech status report send.
##### END #####
13:07:42  INFO: [TTN] thethings.abc.io RTT 100
13:07:42  INFO: [TTN] send status success for thethings.abc.io
13:08:03  INFO: Disabling GPS mode for concentrator's counter...
13:08:03  INFO: host/sx1301 time offset=(1513738260s:921032µs) - drift=-616µs
13:08:03  INFO: Enabling GPS mode for concentrator's counter.
```

However I still don't see the map coming through to our things network console gateway. More tips?

**Comment by kersing** [comment]
Check the metadata for a packet send by a node to see if it contains the GPS data. If it does the gateway is configured correctly and you need to look elsewhere.

**Comment by xenek** [comment]
I can confirm the gps data is included as metadata when viewing the application traffic. It doesn’t show as metadata when viewing the gateway traffic. I’ll search further elsewhere to work out why the general location in out TTI instance hasn’t updated. Thanks!
