### ISSUE TITLE
AEP - Beacon/GPS Disabled

### ISSUE THREAD

**Issue by nick-atmosphereiot** [kersing/multitech-installer#20]
Hi,

I tried to create a thread on TTN forum, but I have no button to post threads there, but I get a "you are not permitted to view the requested resource" error every time I try to post, no matter where. Any chance you could help me with that?

Anyway, I'm trying to set up my conduit with TTN. I've run the installer, and my gateway does seem to be able to communicate with TTN. However, when I look at the AEP console, I see the following:
![image](https://user-images.githubusercontent.com/18118700/59712315-f7ee5300-91da-11e9-91ae-1a809cfa2f99.png)

This seems to indicate that LoRA is disabled. Is this a separate step I must do? Or does the installer generate some config file that this GUI doesn't read in? 

In my logs, I am also seeing some other troubling messages:
```
##### 2019-06-18 18:46:12 GMT #####
### [UPSTREAM] ###
# RF packets received by concentrator: 1
# CRC_OK: 0.00%, CRC_FAIL: 100.00%, NO_CRC: 0.00%
# RF packets forwarded: 0 (0 bytes)
# PUSH_DATA datagrams sent: 0 (0 bytes)
# PUSH_DATA acknowledged: 0.00%
### [DOWNSTREAM] ###
# PULL_DATA sent: 0 (0.00% acknowledged)
# PULL_RESP(onse) datagrams received: 0 (0 bytes)
# RF packets sent to concentrator: 0 (0 bytes)
# TX errors: 0
### BEACON IS DISABLED!
### [JIT] ###
# INFO: JIT queue contains 0 packets.
# INFO: JIT queue contains 0 beacons.
### GPS IS DISABLED!
### [PERFORMANCE] ###
# Upstream radio packet quality: 0.00%.
### [ CONNECTIONS ] ###
# bridge.us-west.thethings.network: Connected
# Semtech status report send.
##### END #####
14:46:12  INFO: [TTN] bridge.us-west.thethings.network RTT 74
14:46:12  INFO: [TTN] send status success for bridge.us-west.thethings.network
admin@mtcdt:~# ##### 2019-06-18 18:46:12 GMT #####
admin@mtcdt:~# ### [UPSTREAM] ###
admin@mtcdt:~# # RF packets received by concentrator: 1
admin@mtcdt:~# # CRC_OK: 0.00%, CRC_FAIL: 100.00%, NO_CRC: 0.00%
admin@mtcdt:~# # RF packets forwarded: 0 (0 bytes)
admin@mtcdt:~# # PUSH_DATA datagrams sent: 0 (0 bytes)
admin@mtcdt:~# # PUSH_DATA acknowledged: 0.00%
admin@mtcdt:~# ### [DOWNSTREAM] ###
admin@mtcdt:~# # PULL_DATA sent: 0 (0.00% acknowledged)
admin@mtcdt:~# # PULL_RESP(onse) datagrams received: 0 (0 bytes)
admin@mtcdt:~# # RF packets sent to concentrator: 0 (0 bytes)
admin@mtcdt:~# # TX errors: 0
admin@mtcdt:~# ### BEACON IS DISABLED!
admin@mtcdt:~# ### [JIT] ###
admin@mtcdt:~# # INFO: JIT queue contains 0 packets.
admin@mtcdt:~# # INFO: JIT queue contains 0 beacons.
admin@mtcdt:~# ### GPS IS DISABLED!
admin@mtcdt:~# ### [PERFORMANCE] ###
admin@mtcdt:~# # Upstream radio packet quality: 0.00%.
admin@mtcdt:~# ### [ CONNECTIONS ] ###
admin@mtcdt:~# # bridge.us-west.thethings.network: Connected
admin@mtcdt:~# # Semtech status report send.
admin@mtcdt:~# ##### END #####
admin@mtcdt:~# 14:46:12  INFO: [TTN] bridge.us-west.thethings.network RTT 74
```

Why is it that GPS and Beacon are disabled? 

Any help would be greatly appreciated,
Nick

**Comment by kersing** [comment]
For the forum: new users need to spend some time reading before you can post messages.

The log shows the software is running fine. This packet forwarder is not integrated into the GUI so after running the installer you should ignore it.

Beacon is always disabled. That requires Class B support which TTN does not (yet) have so there is no use in enabling it.
GPS is disabled because it has not been configured. If your unit has a GPS you can enable it by manually editing some files.

**Comment by nick-atmosphereiot** [comment]
Thanks for the reply. I'm having a couple more issues that I'm hoping you can help me with:

1.) I'm able to activate via OTAA, but sometimes it takes many attempts. I noticed that in my log file on the gateway, it only outputs every 30 seconds or so. It seems like if I start the OTAA process right after I get a print in that log file, it succeeds. Otherwise, it seems like my LORA boad (RN2903) times out and gives up. Is there any way to increase the frequency or responsiveness of the gateway packet handling?

2.) I'm not able to get any actual data to the things network. In my device data log, I'm just seeing a bunch of activation messages:
![image](https://user-images.githubusercontent.com/18118700/59787058-9ee3f500-9296-11e9-970d-9309174105d2.png)


Is there anything manual I should have to do to get the device to show up? I see the gateway sending data to the server when I expect my LORA board to transmit:

```
lgw_receive:1165: FIFO content: 1 75 2 5 11
lgw_receive:1184: [3 17]
Note: LoRa packet
13:32:20  INFO: [up] TTN lora packet send to server "bridge.us-west.thethings.network"
```

Thanks,
Nick

**Comment by kersing** [comment]
The updates of the log every 30 seconds is caused by the log being buffered in memory, every 30 seconds the amount of output exceeds the buffer size causing the buffer to be flushed to disk and being available for any process reading the data.

For the node join issues, check the gateway traffic page in TTN console.

For further support use the TTN forum.
