### ISSUE TITLE
Check firmware version before install

### ISSUE THREAD

**Issue by FokkeZB** [kersing/multitech-installer#5]
@danicampora reported the following issue:

> After starting the ttn-packet-forwarder, I check the logs and I get:

```
admin@mtcdt:~# tail /var/log/lora-pkt-fwd.log
INFO: Radiostream data is enabled
INFO: Statusstream data is enabled
INFO: Beacon is disabled
INFO: Monitor is disabled
INFO: Contact email configured to "daniel@pycom.io"
INFO: Description configured to "Pycom TTN Playground Gateway"
INFO: Successfully contacted server router.eu.thethings.network
INFO: [main] Starting the concentrator
ERROR: Version of calibration firmware not expected, actual:3 expected:2
ERROR: [main] failed to start the concentrator
```

As it turned out he was using a Multitech AEP with firmware version 1.2.2. After [upgrading](http://www.multitech.net/developer/downloads/) to 1.3.2 it worked.

So, the installer should check the firmware version and point users to http://www.multitech.net/developer/downloads/ if their firmware version is out-dated (or at least before 1.3.x)

**Comment by kersing** [comment]
I'm not convinced 1.3.2 is required. This error has been reported before and disappeared after a reboot and clean download of the global_conf.json file. Needs testing.

**Comment by FokkeZB** [comment]
So maybe we should at least document how you'd notice you have this issue (other then checking the logs like @danicampora did) and what to do (reboot). How would people notice?

**Comment by kersing** [comment]
The new installer includes a notice to check the gateway status in the TTN console.
